language: cpp

matrix:
  include:
    - os: linux
      script:
        - ./autogen.sh
        - ./build-windows-binaries.sh
        - ./build-windows-package.sh
    - os: linux
      script:
        - ./autogen.sh
        - ./build-linux-binaries.sh
    - os: linux
      script:
        - ./autogen.sh
        - ./build-linux-package.sh -S
    - os: osx
      script:
        - ./autogen.sh
        - ./build-mac-binaries.sh
