language: cpp

matrix:
  include:
    - os: linux
    - os: osx

script:
  - ./autogen.sh
  - |
    mkdir build &&
    cd build &&
    ../configure &&
    make &&
    (make check || cat build/test/dotests.pl.log) &&
    sudo make install
